services:
  vault-unsealer-tpm:
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    image: vault-unsealer-tpm:latest
    restart: unless-stopped
    devices:
      - /dev/tpmrm0:/dev/tpmrm0
    volumes:
      - vault-unsealer-keys:/keys:ro
      - ./certs:/certs:ro
    environment:
      VAULT_UNSEALER_VAULT_ADDR: "https://vault.example.com:8200"
      VAULT_UNSEALER_VAULT_TLS_CA_CERT: "/certs/ca.pem"
      # VAULT_UNSEALER_VAULT_TLS_SERVER_NAME: "vault.example.com"
      VAULT_UNSEALER_STORE_PATH: "/keys"
      VAULT_UNSEALER_TPM_DEVICE: "/dev/tpmrm0"
      VAULT_UNSEALER_TPM_HANDLE: "0x81010001"
    read_only: true
    security_opt:
      - no-new-privileges:true

  unsealer-init:
    profiles: [init]
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    image: vault-unsealer-tpm:latest
    command: ["-init"]
    stdin_open: true
    tty: true
    devices:
      - /dev/tpmrm0:/dev/tpmrm0
    volumes:
      - vault-unsealer-keys:/keys
      - ./certs:/certs:ro
    environment:
      VAULT_UNSEALER_VAULT_ADDR: "https://vault.example.com:8200"
      VAULT_UNSEALER_VAULT_TLS_CA_CERT: "/certs/ca.pem"
      # VAULT_UNSEALER_VAULT_TLS_SERVER_NAME: "vault.example.com"
      VAULT_UNSEALER_STORE_PATH: "/keys"
      VAULT_UNSEALER_TPM_DEVICE: "/dev/tpmrm0"
      VAULT_UNSEALER_TPM_HANDLE: "0x81010001"
    read_only: true
    security_opt:
      - no-new-privileges:true

volumes:
  vault-unsealer-keys:
